; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; resert CPU on debug 'monitor reset halt'
[env:nucleo_h753zi]
platform = ststm32
;board = nucleo_g474re
board = nucleo_h753zi
framework = stm32cube
board_build.ldscript = linker/STM32H753ZITX_FLASH_FMKNVM.ld
board_upload.maximum_size = 1048576

build_src_filter =
    +<*>
    -<4_PCSIM/**>

build_flags = 
    ;-DDEBUG
    -Isrc/0_Common
    -Isrc/1_FMK 
    -Isrc/2_DRV
    -Isrc/3_APP

upload_protocol = stlink
debug_tool = stlink

[env:pc_sim_debug]
platform = native
build_type = debug
build_src_filter =
    +<0_Common/**>
    +<1_FMK/FMK_HAL/FMK_NVM/Src/FMK_NVM.c>
    +<3_APP/**>
    +<4_PCSIM/**>
    -<3_APP/main.c>
build_flags =
    -DPC_SIM
    -DSTM32H753xx
    -Isrc/0_Common
    -Isrc/1_FMK
    -Isrc/3_APP
    -Isrc/4_PCSIM
    -isystem C:/Users/${sysenv.USERNAME}/.platformio/packages/framework-stm32cubeh7/Drivers/STM32H7xx_HAL_Driver/Inc
    -isystem C:/Users/${sysenv.USERNAME}/.platformio/packages/framework-stm32cubeh7/Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -isystem C:/Users/${sysenv.USERNAME}/.platformio/packages/framework-stm32cubeh7/Drivers/CMSIS/Include
    -lws2_32
debug_build_flags =
    -O0
    -g3

[spi_test_common]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
    +<0_Common/**>
    +<1_FMK/FMK_HAL/FMK_SPI/Src/FMK_SPI.c>
    +<4_PCSIM/pc_sim_fmk_spi_test_mock.c>
    +<4_PCSIM/pc_sim_fmk_spi_test_main.c>
build_flags =
    -DPC_SIM
    -DFMKSPI_TEST_BACKEND
    -DSTM32H753xx
    -Isrc/0_Common
    -Isrc/1_FMK
    -Itest/fmk_spi_support
    -isystem C:/Users/${sysenv.USERNAME}/.platformio/packages/framework-stm32cubeh7/Drivers/STM32H7xx_HAL_Driver/Inc
    -isystem C:/Users/${sysenv.USERNAME}/.platformio/packages/framework-stm32cubeh7/Drivers/CMSIS/Device/ST/STM32H7xx/Include
    -isystem C:/Users/${sysenv.USERNAME}/.platformio/packages/framework-stm32cubeh7/Drivers/CMSIS/Include

[env:pc_spi_master_test]
extends = spi_test_common
test_filter = test_fmk_spi_master

[env:pc_spi_slave_test]
extends = spi_test_common
test_filter = test_fmk_spi_slave
build_flags =
    ${spi_test_common.build_flags}
    -DFMKSPI_TEST_SLAVE_CONFIGURATION
